### ISSUE TITLE
Clarification to IIAs mapping

### ISSUE THREAD

**Issue by jiripetrzelka** [erasmus-without-paper/ewp-specs-api-iia-approval-cnr#4]
"Clients and servers MUST NOT use IIA Approval CNR API for agreements that are not properly mapped (do not provide partner agreement ID)."

By "providing partner agreement ID" you mean that the matching IIA must be visible in the IIA Index endpoint and obtainable through the IIA Get endpoint of the university which invoked the IIA Approval CNR?

**Comment by kamil-olszewski-uw** [comment]
> By "providing partner agreement ID" you mean that the matching IIA must be visible in the IIA Index endpoint and obtainable through the IIA Get endpoint of the university which invoked the IIA Approval CNR?

Yes, that's the point.
